// UK Cities for Coach Location Selection
export const UK_CITIES = [
  // England — Major Cities
  'London',
  'Birmingham',
  'Manchester',
  'Leeds',
  'Sheffield',
  'Liverpool',
  'Bristol',
  'Newcastle',
  'Nottingham',
  'Leicester',
  'Southampton',
  'Brighton',
  'Cambridge',
  'Oxford',
  'York',
  'Bath',
  'Norwich',
  'Exeter',
  'Plymouth',
  'Coventry',
  'Reading',
  'Derby',
  'Portsmouth',
  'Bournemouth',
  'Milton Keynes',
  'Swindon',
  'Northampton',
  'Luton',
  'Wolverhampton',
  'Stoke-on-Trent',
  'Preston',
  'Hull',
  'Bradford',
  'Wakefield',
  'Huddersfield',
  'Doncaster',
  'Bolton',
  'Salford',
  'Blackpool',
  // England — Additional Cities & Large Towns
  'Middlesbrough',
  'Sunderland',
  'Gateshead',
  'Durham',
  'Carlisle',
  'Blackburn',
  'Burnley',
  'Lancaster',
  'Rochdale',
  'Oldham',
  'Wigan',
  'Warrington',
  'Chester',
  'Crewe',
  'Stockport',
  'Macclesfield',
  'Shrewsbury',
  'Telford',
  'Hereford',
  'Worcester',
  'Gloucester',
  'Cheltenham',
  'Salisbury',
  'Winchester',
  'Guildford',
  'Woking',
  'Crawley',
  'Hastings',
  'Eastbourne',
  'Worthing',
  'Folkestone',
  'Canterbury',
  'Maidstone',
  'Chatham',
  'Colchester',
  'Ipswich',
  'Peterborough',
  'Lincoln',
  'Grimsby',
  'Scunthorpe',
  'Walsall',
  'West Bromwich',
  'Dudley',
  'Solihull',
  'Redditch',
  'Kidderminster',
  'Chesterfield',
  'Mansfield',
  'Harrogate',
  'Scarborough',
  'Rotherham',
  'Barnsley',
  'St Albans',
  'Stevenage',
  'Watford',
  'Hemel Hempstead',
  'Chelmsford',
  'Southend-on-Sea',
  'Basildon',
  'Slough',
  'Windsor',
  'High Wycombe',
  'Basingstoke',
  'Aldershot',
  'Chichester',
  'Torquay',
  'Truro',
  'Newquay',
  'Barnstaple',
  // Scotland
  'Glasgow',
  'Edinburgh',
  'Aberdeen',
  'Dundee',
  'Inverness',
  'Stirling',
  'Perth',
  'Falkirk',
  'Livingston',
  'Kilmarnock',
  'Ayr',
  'Dumfries',
  'St Andrews',
  'Fort William',
  // Wales
  'Cardiff',
  'Swansea',
  'Newport',
  'Wrexham',
  'Bangor',
  'Aberystwyth',
  'Llanelli',
  'Merthyr Tydfil',
  'Pontypridd',
  // Northern Ireland
  'Belfast',
  'Derry',
  'Lisburn',
  'Newry',
  'Armagh',
  'Ballymena',
  'Coleraine',
  'Omagh',
  // Remote / Custom
  'Other',
] as const;

export type UKCity = typeof UK_CITIES[number];

// Location Radius Options (for in-person coaching)
export const LOCATION_RADIUS_OPTIONS = [
  { value: '5', label: 'Within 5 miles' },
  { value: '10', label: 'Within 10 miles' },
  { value: '25', label: 'Within 25 miles' },
  { value: '50', label: 'Within 50 miles' },
  { value: 'nationwide', label: 'Nationwide (UK)' },
  { value: 'international', label: 'International' },
] as const;

export type LocationRadius = typeof LOCATION_RADIUS_OPTIONS[number]['value'];

// Helper function to format location display
export function formatLocation(city: string, radius?: string): string {
  if (!radius) return city;

  const radiusOption = LOCATION_RADIUS_OPTIONS.find(opt => opt.value === radius);
  const radiusLabel = radiusOption ? radiusOption.label.toLowerCase() : radius;

  return `${city} (${radiusLabel})`;
}

// Helper to check if location is valid UK city
export function isValidUKCity(city: string): boolean {
  return UK_CITIES.includes(city as UKCity);
}
